### ISSUE TITLE
ShadowHelper报这个错 No static method setBackground

### ISSUE THREAD

**Issue by MYaoDan** [liujinchao/XSelectorUtil#1]
建议加上这个代码
`
int sdk = android.os.Build.VERSION.SDK_INT;
if(sdk < android.os.Build.VERSION_CODES.JELLY_BEAN) {
   ViewCompat.setBackgroundDrawable(view, drawable);
} else {
   ViewCompat.setBackground(view, drawable);
}
`

**Comment by liujinchao** [comment]
谢谢提问，关于ViewCompat类主要是用来提供兼容性的，可以查看一下`ViewCompat.setBackground(@NonNull View view, @Nullable Drawable background)`源码：
```
public static void setBackground(@NonNull View view, @Nullable Drawable background) {
        if (VERSION.SDK_INT >= 16) {
            view.setBackground(background);
        } else {
            view.setBackgroundDrawable(background);
        }

    }
```
如还有疑问，可把使用方法贴出来看下

**Comment by MYaoDan** [comment]
但是出现兼容的问题No static method setBackground，导入项目后，库找不到这个方法
