### ISSUE TITLE
这个可以在ImageView上设置吗

### ISSUE THREAD

**Issue by hfkai** [liujinchao/XSelectorUtil#2]

**Comment by liujinchao** [comment]
如果使用background可以使用，不能使用设置字体颜色的属性，注意需要将ImageView的clickable属性置为true。

**Comment by hfkai** [comment]
圆角的ImageView也可以用这个？大佬可以写个例子吗？我试了下，好像不行

**Comment by liujinchao** [comment]
把你的代码使用方法贴出来
